### ISSUE TITLE
[SPRING] The privacy manager displays special characters wrong

### ISSUE THREAD

**Issue by s-hintz** [SourcePointUSA/ios-cmp-app#217]
&amp;
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-07-27 at 16 27 27](https://user-images.githubusercontent.com/39526001/88554163-78aa9000-d026-11ea-9dcf-615e710be3b8.png)

And the left margin is wrong.
And I do think that the BILD iOS apps do not most of the vendors.

**Comment by atanurdemirci** [comment]
Hi @s-hintz confirming that we've an internal task to resolve this issue, will post an update here on once finished. 
Thanks,
Atanur

**Comment by haerju** [comment]
@s-hintz This issue is resolved now. @andresilveirah This issue can be closed.

**Comment by s-hintz** [comment]
I just did a quick look on https://www.welt.de/services/article213568360/Privatsphaere-WELT-Digital.html an I still see the problem.
<img width="809" alt="Bildschirmfoto 2020-11-02 um 08 37 59" src="https://user-images.githubusercontent.com/39526001/97841867-f3024480-1ce6-11eb-8930-37efa4298522.png">

**Comment by s-hintz** [comment]
Where did you fix it?
I also still see it in our app.
![Simulator Screen Shot - iPod touch (7th generation) - 2020-11-02 at 08 46 10](https://user-images.githubusercontent.com/39526001/97842512-019d2b80-1ce8-11eb-8171-a2ad28285558.png)

**Comment by s-hintz** [comment]
And I see a new problem.
The blue cursors of the text input field is still visible after scrolling when the input it not visible anymore.

**Comment by haerju** [comment]
@s-hintz Both issues are solved. The cursor issue requires an update of your privacy manager that currently sits in staging and needs to be updated by your project team.

@andresilveirah this issue can be solved.
